### ISSUE TITLE
What a crazy idea!!!

### ISSUE THREAD

**Issue by elmar-hinz** [typo3-themes/theme_adapter_wordpress#1]
Sorry, 

I found no other way to give feedback.

Go on!

\Elmar

**Comment by kaystrobach** [comment]
hi elmar,

no problem with feedback :d

Yeah i also think about adapters to other templating systems.
EXT:Themes is able to handle almost anything (even if wordpress is really hard to handle - the code is really really ugly ...)

If you want you may contact me via my github username on skype :D

PS: i got it basicly working with these skins:
- buttercream - http://carolinethemes.com/2012/03/13/buttercream/
- patchwork - http://carolinethemes.com/2012/02/21/new-theme-patchwork/
- responsive - http://themeid.com/responsive-theme/ 
- twentytwelve - http://wordpress.org/extend/themes/twentytwelve

Regards
Kay

**Comment by webian** [comment]
I also think that the possibility to use the many and good quality Wordpress themes in TYPO3 is amazing!
But, why is this porting marked as deprecated?
Is it merged somewhere else?

**Comment by kaystrobach** [comment]
it's simply the crappy codequality of wordpress themes, which makes this concept obsolete. The current plan is to use a webservice to convert wordpress themes into useable TYPO3 Themes (render + add markers).
A normal Wordpress Theme is a really bad mixture of PHP and HTML. I tried to implement this, but then we would have all the unsecure code in our TYPO3 Installations ...

**Comment by webian** [comment]
Then maybe the term "deprecated" is misleading cause it means that something else replaced this one.

**Comment by kaystrobach** [comment]
there will be a replacement ;)
